{
 "title": "阿里云 RDS 状态监控",
 "description": "阿里云 RDS 状态监控",
 "tags": [
  "RDS",
  "detail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instanceId",
    "query": "label_values(aliyun_rds_performance_MySQL_MemCpuUsage_cpuusage, instanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "MySQL_CpuUsage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_MemCpuUsage_cpuusage{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{CPU使用率}}"
    }
   ]
  },
  {
   "title": "MySQL_MemUsage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_MemCpuUsage_memusage{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{内存使用率}}"
    }
   ]
  },
  {
   "title": "MySQL_NetworkTraffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_NetworkTraffic_recv_k{instanceId=\"$instanceId\"}",
     "legendFormat": "{{平均每秒钟的输入流量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_NetworkTraffic_sent_k{instanceId=\"$instanceId\"}",
     "legendFormat": "{{每秒钟的输出流量}}"
    }
   ]
  },
  {
   "title": "MySQL_Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_Sessions_active_session{instanceId=\"$instanceId\"}",
     "legendFormat": "{{当前活跃连接数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_Sessions_total_session{instanceId=\"$instanceId\"}",
     "legendFormat": "{{当前总连接数}}"
    }
   ]
  },
  {
   "title": "MySQL_IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_IOPS_value{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{IOPS（每秒IO请求次数）}}"
    }
   ]
  },
  {
   "title": "MySQL_QPSTPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_QPSTPS_QPS{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{ 平均每秒SQL语句执行次数 }}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_QPSTPS_TPS{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{ 平均每秒事务数 }}"
    }
   ]
  },
  {
   "title": "MySQL_DetailedSpaceUsage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_DetailedSpaceUsage_ins_size{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{磁盘空间总体使用量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_DetailedSpaceUsage_data_size{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{数据空间使用量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_DetailedSpaceUsage_log_size{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{日志空间使用量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_DetailedSpaceUsage_tmp_size{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{临时文件空间使用量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_DetailedSpaceUsage_other_size{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{系统文件空间使用量}}"
    }
   ]
  },
  {
   "title": "MySQL_COMDML",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_insert{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Insert语句执行次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_delete{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Delete语句执行次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_update{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Update语句执行次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_select{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Select语句执行次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_insert_select{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Insert_Select语句执行次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_replace_select{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒Replace_Select语句执行次数}}"
    }
   ]
  },
  {
   "title": "MySQL_RowDML",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_insert{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒从InnoDB表插入的行数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_delete{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒从InnoDB表删除的行数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_readed{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒从InnoDB表读取的行数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_update{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒从InnoDB表更新的行数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_Inno_log_writes{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒向日志文件的物理写次数}}"
    }
   ]
  },
  {
   "title": "MySQL_TempDiskTableCreates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_TempDiskTableCreates_value{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{执行语句时在硬盘上自动创建的临时表的数量}}"
    }
   ]
  },
  {
   "title": "MySQL_InnoDBDataReadWriten",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBDataReadWriten_inno_data_read{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{InnoDB平均每秒钟读取的数据量}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBDataReadWriten_inno_data_written{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{InnoDB平均每秒钟写入的数据量}}"
    }
   ]
  },
  {
   "title": "MySQL_InnoDBBufferRatio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_dirty_ratio{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{InnoDB缓冲池脏块的百分率}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_read_hit{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{InnoDB缓冲池的读命中率}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_use_ratio{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{InnoDB缓冲池的使用率}}"
    }
   ]
  },
  {
   "title": "MySQL_InnoDBLogRequests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogRequests_ibuf_request_r{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒向InnoDB缓冲池的读次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogRequests_ibuf_request_w{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒向InnoDB缓冲池的写次数}}"
    }
   ]
  },
  {
   "title": "MySQL_InnoDBLogWrites",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_log_write_requests{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒日志写请求数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_log_writes{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒向日志文件的物理写次数}}"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_os_log_fsyncs{instanceId=~\"$instanceId\"}",
     "legendFormat": "{{平均每秒向日志文件完成的fsync()写数量}}"
    }
   ]
  }
 ]
}